# Generated by Django 3.2.13 on 2022-05-08 06:52

from django.db import migrations, models
import django.db.models.deletion
import viewbooks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EngBooksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=viewbooks.models.upload_location)),
                ('b_date', models.DateField(blank=True, null=True)),
                ('free', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='RusBooksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=viewbooks.models.upload_location)),
                ('b_date', models.DateField(blank=True, null=True)),
                ('free', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UzbBooksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=viewbooks.models.upload_location)),
                ('b_date', models.DateField(blank=True, null=True)),
                ('free', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='BuyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.PositiveBigIntegerField(verbose_name=998)),
                ('adres', models.TextField(max_length=255)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyurtma', to='viewbooks.uzbbooksmodel')),
            ],
        ),
    ]
