# Generated by Django 3.2.13 on 2022-05-08 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewbooks', '0002_alter_buymodel_tel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buymodel',
            old_name='tel',
            new_name='telefon raqam',
        ),
    ]
