# Generated by Django 3.2.13 on 2022-05-10 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewbooks', '0005_auto_20220508_1538'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BuyModel',
            new_name='UzBuyModel',
        ),
        migrations.CreateModel(
            name='RusBuyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ваш номер телефон номер:', models.PositiveBigIntegerField()),
                ('Адрес:', models.TextField(max_length=255)),
                ('Называния книги:', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewbooks.rusbooksmodel')),
            ],
        ),
        migrations.CreateModel(
            name='EngBuyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone number:', models.PositiveBigIntegerField()),
                ('Address:', models.TextField(max_length=255)),
                ('The book name:', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewbooks.engbooksmodel')),
            ],
        ),
    ]
