# Generated by Django 3.2.13 on 2022-05-15 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewbooks', '0006_auto_20220510_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engbooksmodel',
            name='free',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='rusbooksmodel',
            name='free',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='uzbbooksmodel',
            name='free',
            field=models.BooleanField(null=True),
        ),
    ]
