# Generated by Django 4.0.5 on 2022-06-29 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewbooks', '0007_auto_20220515_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engbooksmodel',
            name='free',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engbuymodel',
            name='The book name:',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='viewbooks.engbooksmodel'),
        ),
        migrations.AlterField(
            model_name='rusbooksmodel',
            name='free',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rusbuymodel',
            name='Называния книги:',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='viewbooks.rusbooksmodel'),
        ),
        migrations.AlterField(
            model_name='uzbbooksmodel',
            name='free',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uzbuymodel',
            name='Kitob nomi:',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='viewbooks.uzbbooksmodel'),
        ),
    ]
