# Generated by Django 4.0.5 on 2022-06-29 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewbooks', '0009_rename_the book name:_engbuymodel_kitob_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engbuymodel',
            old_name='Kitob',
            new_name='kitob',
        ),
        migrations.RenameField(
            model_name='rusbuymodel',
            old_name='Kitob',
            new_name='kitob',
        ),
        migrations.RenameField(
            model_name='uzbuymodel',
            old_name='Kitob',
            new_name='kitob',
        ),
    ]
