# Generated by Django 4.0.5 on 2022-06-29 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewbooks', '0010_rename_kitob_engbuymodel_kitob_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uzbuymodel',
            old_name='telefon raqam:',
            new_name='tel',
        ),
    ]
