# Generated by Django 4.0.5 on 2022-06-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewbooks', '0011_rename_telefon raqam:_uzbuymodel_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='engbuymodel',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='rusbuymodel',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='uzbuymodel',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
