# Generated by Django 4.0.5 on 2022-07-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewbooks', '0014_alter_uzbuymodel_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engbuymodel',
            name='telephone number:',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rusbuymodel',
            name='ваш номер телефон номер:',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
