# Generated by Django 4.0.5 on 2022-07-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewbooks', '0015_alter_engbuymodel_telephone number:_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engbooksmodel',
            name='user',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='engbooksmodel',
            name='whose',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rusbuymodel',
            name='user',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rusbuymodel',
            name='whose',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uzbuymodel',
            name='user',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uzbuymodel',
            name='whose',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
